version : "3.9"

services:
  web:
    build: .
    container_name: bug_tracker_app
    ports: 
      - "8080:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/bugtracker
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: bug_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bugtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    
